

services:

  nginx:
    build: requirements/nginx/.
    image: nginx
    container_name: nginx
    ports: 
      - "443:443"
    volumes:
      - /home/lg/lgottsch/data/wordpress:/var/www/html
    networks:
      - inception
    restart: unless-stopped
    env_file: .env


  mariadb:
    build: requirements/mariadb/.
    image: mariadb
    container_name: mariadb
    volumes:
      - /home/lg/lgottsch/data/database:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
    env_file: .env



  wordpress:
    build: requirements/wordpress/.
    image: wordpress
    container_name: wordpress
    volumes:
      - /home/lg/lgottsch/data/wordpress:/var/www/html
    networks:
      - inception
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mariadb


networks:
  inception:
    driver: bridge
